### ISSUE TITLE
Underscores in identifiers: text/example mismatch

### ISSUE THREAD

**Issue by OJacot-Descombes** [ktaranov/naming-convention#10]
Point 8, ["Do not use Underscores in identifiers."](https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md#8-do-not-use-underscores-in-identifiers-exception-you-can-prefix-private-static-variables-with-an-underscore) says: _"Exception: you can prefix private static variables with an underscore"_, but example shows instance variable

```
// Exception (Class field)
private DateTime _registrationDate;
```

I think it would be okay to prefix fields (instance variables) with an underscore.

**Comment by ktaranov** [comment]
Hi @OJacot-Descombes , I agree with your opinion. Could you prepare pull request for this improvement (if you need any help with github stuff I can help you)?

**Comment by ktaranov** [comment]
Closed via https://github.com/ktaranov/naming-convention/pull/12
