### ISSUE TITLE
Suggestion for predefined type names

### ISSUE THREAD

**Issue by OJacot-Descombes** [ktaranov/naming-convention#11]
Point 9, ["Do use predefined type names instead of system type names like Int16, Single, UInt64, etc."](https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md#9-do-use-predefined-type-names-instead-of-system-type-names-like-int16-single-uint64-etc).

I usually use the C# aliases (predefined types) for locals, parameters and members declarations, but the Framework names when accessing the type's static members like `Int32.TryParse` or `String.Join`. Suggestion: You could add this as an exception.

**Comment by ktaranov** [comment]
Hi, @OJacot-Descombes . Also agree with this request. Could you add pull request? Or (if you did not have enough time) just in answer message type your final version for point 9.

**Comment by ktaranov** [comment]
Closed via https://github.com/ktaranov/naming-convention/pull/13
