### ISSUE TITLE
Invalid code: static const

### ISSUE THREAD

**Issue by snwflake** [ktaranov/naming-convention#14]
In point 4 [Do not use Screaming Caps for constants or readonly variables:](https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md#4-do-not-use-screaming-caps-for-constants-or-readonly-variables) your example uses
```c#
// Correct
public static const string ShippingType = "DropShip";
```
which is invalid. `const` implies `static` and is therefore neither needed, nor allowed.

**Comment by ktaranov** [comment]
Hi, @snwflake. Thanks for issue. Could you prepare pull request for it?

**Comment by snwflake** [comment]
done.
#15
