### ISSUE TITLE
Question: C# Convention: Is there a convention with calling methods?

### ISSUE THREAD

**Issue by dnsnx** [ktaranov/naming-convention#32]
I've got a question regarding calling methods in C#. Is there a convention, too?
I.e. this function

```
public void DoSomething(string foo, int bar) 
{
...
}
```

In VS I can call this function:

`DoSomething("someString", 1);`

or 

`DoSomething(foo: "someString", bar: 1);`

Is there any convention for this?

**Comment by ktaranov** [comment]
> Is there any convention for this?
No, you can add this convention via PR.
Second variant `DoSomething(foo: "someString", bar: 1);` is much better.

**Comment by ktaranov** [comment]
Via https://github.com/ktaranov/naming-convention/pull/33
