### ISSUE TITLE
FileName/SlnName/CSprojName Standards

### ISSUE THREAD

**Issue by ab12gu** [ktaranov/naming-convention#38]
Hi, 

I don't see you have standards for these above. Do you have a recommended standard for these or could I commit a standard that I work with?

Best, 

Abhay Gupta

**Comment by ktaranov** [comment]
@ab12gu I can not find standards recommended by microsoft, you could add your convention and create pr.

**Comment by TsgabiXD** [comment]
Hello there,

I'm very interested in the FileName Conventions but I can't find any... (probably weak googling)
@ab12gu may you tell me were your knowledge originates?

BG
Tobias
