### ISSUE TITLE
naming convention of Field is not accurate in C#

### ISSUE THREAD

**Issue by md-redwan-hossain** [ktaranov/naming-convention#41]
public field name should be `PascalCase`. [Source](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#:~:text=When%20naming%20public%20members%20of%20types%2C%20such%20as%20fields%2C%20properties%2C%20events%2C%20methods%2C%20and%20local%20functions%2C%20use%20pascal%20casing.)
private field name should be `_camelCase`. [Source](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#:~:text=Use%20camel%20casing%20(%22camelCasing%22)%20when%20naming%20private%20or%20internal%20fields%2C%20and%20prefix%20them%20with%20_.)

**Comment by ktaranov** [comment]
@md-redwan-hossain thanks fixed via https://github.com/ktaranov/naming-convention/commit/86883747bffd778414896bc56ba85b0ae967465d
